[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/memories"
  to = "/.netlify/functions/memories"
  status = 200

[[redirects]]
  from = "/api/file"
  to = "/.netlify/functions/file"
  status = 200

[[redirects]]
  from = "/events"
  to = "/.netlify/functions/events"
  status = 200
